[project]
name = "blocstage"
version = "0.1.0"

[cors]
allowed_origins = ["https://blocstage.com", "http://localhost:3000"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization", "Accept", "X-Requested-With", "Origin"]
max_age = 3600

[rate_limiting]
requests_per_minute = 100

[compression]
enabled = true

[security_headers]
x_content_type_options = "nosniff"
x_frame_options = "DENY"
x_xss_protection = "1; mode=block"